// Curated short quotes for motivation notifications & the home carousel.
// Kept intentionally brief (under ~15 words) with clear attribution.
// Each has an `img` seed used to generate a consistent background photo.
const QUOTES = [
  { text: "We suffer more in imagination than in reality.", author: "Seneca", img: "mountain-dawn" },
  { text: "You have power over your mind, not outside events.", author: "Marcus Aurelius", img: "stone-steps" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca", img: "hourglass-light" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius", img: "cliff-edge" },
  { text: "Man is disturbed not by things, but by the views he takes of them.", author: "Epictetus", img: "still-lake" },
  { text: "First say to yourself what you would be, then do what you have to do.", author: "Epictetus", img: "open-road" },
  { text: "The unexamined life is not worth living.", author: "Socrates", img: "old-library" },
  { text: "Well begun is half done.", author: "Aristotle", img: "sunrise-field" },
  { text: "We are what we repeatedly do. Excellence, then, is a habit.", author: "Aristotle", img: "gym-dawn" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", img: "mountain-fog" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche", img: "storm-ridge" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi", img: "desert-dune" },
  { text: "The wound is the place where the light enters you.", author: "Rumi", img: "forest-light" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", img: "quiet-shore" },
  { text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle", img: "orchard-row" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela", img: "summit-view" },
  { text: "I have not failed. I've just found ten thousand ways that won't work.", author: "Thomas Edison", img: "workshop-desk" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs", img: "empty-highway" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", img: "sunlit-desk" },
  { text: "I failed my way to success.", author: "Thomas Edison", img: "old-bulb" },
  { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats", img: "forge-glow" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln", img: "wheat-field" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", img: "river-bend" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius", img: "rocky-path" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius", img: "canyon-light" },
  { text: "What we think, we become.", author: "Buddha", img: "bamboo-grove" },
  { text: "The mind is everything. What you think you become.", author: "Buddha", img: "temple-mist" },
  { text: "Small daily improvements are the key to staggering long-term results.", author: "Popular proverb", img: "staircase-light" },
  { text: "Do the hard jobs first. The easy jobs will take care of themselves.", author: "Dale Carnegie", img: "early-desk" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", img: "factory-line" },
  { text: "Quality means doing it right when no one is looking.", author: "Henry Ford", img: "workbench" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", img: "young-forest" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb", img: "snow-peak" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", img: "empty-court" },
  { text: "Amateurs sit and wait for inspiration; the rest of us just get up and go to work.", author: "Stephen King", img: "typewriter-desk" },
  { text: "Someday is not a day of the week.", author: "Denise Brennan-Nelson", img: "calendar-blur" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun", img: "trail-run" },
  { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "Common proverb", img: "clockwork" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu", img: "footpath-woods" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu", img: "waterfall-calm" },
  { text: "The best way out is always through.", author: "Robert Frost", img: "tunnel-light" },
];
